---

# Numpy para análisis de datos

Numpy para trabajar con arrays:
Los arrays puere ser de dos tipos:
vectores - son arrays de 1 dimención (una sola fila) y matrices - son arrays de 2 dimeciones (1, o más filas y 1 o más columnas)


Un array en programación, especialmente en Python con numpy, es una estructura de datos utilizada para almacenar múltiples elementos del mismo tipo, organizados en una secuencia ordenada.

Eficiencia: Arrays permiten realizar operaciones matemáticas y estadísticas de manera rápida y eficiente.

Manipulación: Facilitan la manipulación y análisis de grandes conjuntos de datos.

Funciones: Permiten usar funciones específicas como reshape para cambiar su forma sin cambiar sus datos.

In [157]:
#1. Eficiencia
#Los arrays de numpy son más eficientes en términos de memoria y velocidad que las listas de Python. Esto se debe a que numpy 
#almacena los datos de manera contigua en memoria, lo que permite operaciones más rápidas y uso eficiente del caché del CPU.

#2. Manipulación
#Slicing: Permite extraer subconjuntos de datos. Ejemplo:

#python


array = np.array([1, 2, 3, 4, 5])
sub_array = array[1:4]  # Resultado: [2, 3, 4]
#Reshape: Cambia la forma del array sin alterar sus datos.

#python


array = np.array([1, 2, 3, 4, 5, 6])
matrix = array.reshape(2, 3)  # Resultado: array([[1, 2, 3], [4, 5, 6]])
#Concatenation: Combina múltiples arrays.

#python

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
combined = np.concatenate((array1, array2))  # Resultado: [1, 2, 3, 4, 5, 6]
#3.Funciones

In [159]:
array = np.array([1, 2, 3, 4, 5])
sub_array = array[1:4]

In [161]:
sub_array

array([2, 3, 4])

In [163]:
array = np.array([1, 2, 3, 4, 5, 6])
matrix = array.reshape(2, 3)

In [165]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
combined = np.concatenate((array1, array2))

In [167]:
combined 

array([1, 2, 3, 4, 5, 6])

## Numpy con listas

In [6]:
# Numpy arrays

In [8]:
import numpy as np

In [10]:
lista = [1,2,3,4]

In [12]:
array = np.array(lista) # array una dimención

In [14]:
array

array([1, 2, 3, 4])

In [18]:
lista2 = ([1,2,3],[4,5,6], [7,8,9])

In [20]:
lista2

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [22]:
array2 = np.array(lista2) # array de dos dimenciónes

In [24]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Numpy arrays -  funcciónes arange , ones, zeros y linspace

In [30]:
arrays = np.arange(5)

In [32]:
array

array([1, 2, 3, 4])

In [34]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [38]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [40]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [42]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.zeros(3)

array([0., 0., 0.])

In [46]:
np.zeros((3,4)) # tres filas y cuatro columnas

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
np.ones(3)

array([1., 1., 1.])

In [50]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
np.linspace(5,8,50) # desde primero elemento 5, generado 50 elementos hasta ,ultimo 8

array([5.        , 5.06122449, 5.12244898, 5.18367347, 5.24489796,
       5.30612245, 5.36734694, 5.42857143, 5.48979592, 5.55102041,
       5.6122449 , 5.67346939, 5.73469388, 5.79591837, 5.85714286,
       5.91836735, 5.97959184, 6.04081633, 6.10204082, 6.16326531,
       6.2244898 , 6.28571429, 6.34693878, 6.40816327, 6.46938776,
       6.53061224, 6.59183673, 6.65306122, 6.71428571, 6.7755102 ,
       6.83673469, 6.89795918, 6.95918367, 7.02040816, 7.08163265,
       7.14285714, 7.20408163, 7.26530612, 7.32653061, 7.3877551 ,
       7.44897959, 7.51020408, 7.57142857, 7.63265306, 7.69387755,
       7.75510204, 7.81632653, 7.87755102, 7.93877551, 8.        ])

In [56]:
np.linspace(3,9,20)

array([3.        , 3.31578947, 3.63157895, 3.94736842, 4.26315789,
       4.57894737, 4.89473684, 5.21052632, 5.52631579, 5.84210526,
       6.15789474, 6.47368421, 6.78947368, 7.10526316, 7.42105263,
       7.73684211, 8.05263158, 8.36842105, 8.68421053, 9.        ])

In [58]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [60]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Numpy arrays - números aleatorios - rand y randn

In [63]:
np.random.rand(5)

array([0.8791526 , 0.13220312, 0.8674016 , 0.87514674, 0.82819999])

In [65]:
np.random.rand(2,3)

array([[0.07596111, 0.09680597, 0.44362503],
       [0.62746536, 0.95840222, 0.0267556 ]])

In [67]:
np.random.randn(2,3)

array([[ 1.5569954 , -1.18667701,  0.02911528],
       [ 0.63271381, -1.27953475,  0.85023566]])

In [69]:
np.random.randn(4)

array([-0.81934215, -1.34450399,  0.29587359, -0.04880444])

In [71]:
np.random.randn(4,5)

array([[-1.74195571, -0.05002248, -2.60067418,  0.75499849, -0.40348446],
       [-0.4843167 ,  0.46581747,  1.09212822,  0.38975057,  0.80742188],
       [-0.01549408, -0.86605236,  0.56565891, -0.08129522, -0.93908619],
       [-1.47720222,  1.47608076,  0.64052738,  0.02559371,  1.4385157 ]])

## Numpy array - números aleatorios enteros, randint

In [78]:
np.random.randint(1,20)

15

In [80]:
np.random.randint(1,20)

3

In [82]:
np.random.randint(1,20,5)

array([ 5, 11,  3, 13,  2])

## Numpy array - reshape - cambio de tamaño

In [88]:
array = np.random.randint(1,100,25)

In [90]:
array

array([87, 78, 52,  6, 83, 60, 94, 19, 48, 27, 18, 60, 61, 61, 98, 91, 36,
       58, 31, 80, 30, 51, 35, 55, 16])

In [92]:
matriz = array.reshape(5,5)

In [94]:
matriz

array([[87, 78, 52,  6, 83],
       [60, 94, 19, 48, 27],
       [18, 60, 61, 61, 98],
       [91, 36, 58, 31, 80],
       [30, 51, 35, 55, 16]])

In [108]:
array = np.random.randint(1,100,25)

In [108]:
array = np.random.randint(1,100,25)

In [110]:
array

array([40,  4, 33, 91, 97, 24,  3, 28, 42, 27, 31, 81, 24, 55, 99, 74, 70,
       56, 40, 90, 87, 54, 36, 55, 98])

In [118]:
matriz = array.reshape(3,7)
matriz

array([[12, 55, 20, 92, 57, 88, 22],
       [ 7, 90, 49, 71, 65, 31, 85],
       [82,  4, 23,  2, 50, 71, 51]])

In [116]:
array = np.random.randint(1, 100, 21)  # 3x7 = 21
matriz = array.reshape(3, 7)

print(matriz)


[[12 55 20 92 57 88 22]
 [ 7 90 49 71 65 31 85]
 [82  4 23  2 50 71 51]]


## Numpy arrays - valor max y min

In [122]:
array = np.random.randint(1,100,50)

In [124]:
array

array([48, 93, 83, 97,  3, 26, 99, 16,  6, 55, 54, 68, 60, 54, 32, 95, 58,
       69, 63, 66, 66, 43, 78, 61, 19, 78, 62, 93, 84,  5, 80, 21, 85, 47,
       73, 54,  7, 57, 63, 89, 57, 46, 87, 28, 67, 14, 18, 19, 92, 22])

In [126]:
valor_maximo = array.max()

In [128]:
valor_maximo

99

In [132]:
posicion_valor_maximo = array.argmax()

In [134]:
posicion_valor_maximo

6

In [142]:
valor_minimo = array.min()
valor_minimo 

3

In [144]:
posicion_valor_minimo = array.argmin()


In [146]:
posicion_valor_minimo 

4

## Numpy - indexación en array (1 dimención)

In [171]:
array = np.arange(0,10)

In [173]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [175]:
array[0]

0

In [177]:
array[1]

1

In [181]:
array[-1]

9

In [183]:
array[2:4]

array([2, 3])

In [185]:
array[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [187]:
array[5:]

array([5, 6, 7, 8, 9])

In [189]:
array[:4]

array([0, 1, 2, 3])

In [191]:
array2 = array.copy()

In [193]:
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [197]:
array2[0] = 100

In [199]:
array2

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [201]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Numpy - Indexación en arrays (2 o más dimenciónes)

In [204]:
array = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [206]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [208]:
array [0]

array([1, 2, 3])

In [214]:
array2 = array[:2]

In [216]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [218]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [220]:
array[0][0]

1

In [222]:
array[0,0]

1

In [224]:
array[1,1]

5

In [226]:
array[:,0]

array([1, 4, 7])

In [228]:
array[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

## Numpy - Selecciónar elementos de un array según una condición

In [243]:
array = np.arange(1,10)

In [245]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [247]:
condicion = array > 5

In [249]:
condicion

array([False, False, False, False, False,  True,  True,  True,  True])

In [251]:
array[condicion]

array([6, 7, 8, 9])

In [253]:
array6 = array[condición]

In [255]:
array6

array([6, 7, 8, 9])

In [257]:
array[array > 5]

array([6, 7, 8, 9])

In [261]:
array[array < 6]

array([1, 2, 3, 4, 5])

In [263]:
array[array % 2 == 0]

array([2, 4, 6, 8])

In [265]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Operaciónes con arrays

In [268]:
array = np.arange(0,10)

In [270]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [272]:
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [274]:
array * 100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [276]:
array + 40

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [278]:
array - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [282]:
array2 = np.arange(5,15)

In [284]:
array2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [286]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [290]:
array2 - array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [292]:
array2 * array

array([  0,   6,  14,  24,  36,  50,  66,  84, 104, 126])

In [294]:
np.sqrt(array2)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [296]:
np.max(array)

9

In [298]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [302]:
np.min(array)

0

## Ejercicios

### 1.Ejercicio

Crea una lista de números secuenciales con l valor minimo de 10 y el valor maximo 39
Convierte esta lista en una lista o matriz de 2 dimenciónes (3 filas por 10 columnas)
Muestra por pantalla el valor del elemento de la esquina superior derecha de la matriz

In [7]:
import numpy as np

In [9]:
lista = np.arange(10, 40)

In [11]:
lista

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [13]:
lista = lista.reshape(3,10)

In [15]:
lista

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [22]:
lista[0][9]

19

### 2.Ejercicio

Crea un array de una dimención con 9 valores enteros aleatorios entre 0 y 100
Convierte ese array en un matriz de 2 dimenciónes (3 filas y 3 columnas)
Muestra por pantalla el valor del elemento de la matriz, de la esquina inferior derecha

In [28]:
array = np.random.randint(0,100,9)

In [30]:
array

array([16,  4,  9,  2, 54, 12, 39, 45, 69])

In [32]:
matriz = array.reshape(3,3)

In [40]:
matriz

array([[16,  4,  9],
       [ 2, 54, 12],
       [39, 45, 69]])

In [44]:
matriz[2][2]

69

### 3.Ejercicio

#Desarrolla una función llamada generar_numeros_enteros_aleatorios que tome como entrada el número de elementos N, un valor mínimo minimo y un valor máximo maximo, y utilice NumPy para generar una lista de N números enteros aleatorios en el rango [minimo, maximo].



def generar_numeros_enteros_aleatorios(N, minimo, maximo):



#### Ejemplo de uso
N = 5
minimo = 1
maximo = 10
resultado = generar_numeros_enteros_aleatorios(N, minimo, maximo)
print(resultado)
 

In [181]:
import numpy as np

def generar_numeros_enteros_aleatorios(N, minimo, maximo):
    return list(np.random.randint(minimo  , maximo , N ))

# Ejemplo de uso
N = 5
minimo =1
maximo =10
resultado = generar_numeros_enteros_aleatorios(N, minimo, maximo)
resultado 

[8, 7, 4, 6, 6]

In [178]:
import numpy as np

def generar_numeros_enteros_aleatorios(N, minimo, maximo):
    return list(np.random.randint(minimo, maximo + 1, N))

# Ejemplo de uso
N = 5
minimo = 1
maximo = 10
resultado = generar_numeros_enteros_aleatorios(N, minimo, maximo)
print(resultado)  


[4, 1, 7, 10, 4]


In [183]:
import numpy as np

def generar_numeros_enteros_aleatorios(N, minimo, maximo, semilla=None):
    if semilla is not None:
        np.random.seed(semilla)
    return list(np.random.randint(minimo, maximo + 1, N))

# Ejemplo de uso con semilla
N = 5
minimo = 1
maximo = 10
semilla = 42  # Puedes elegir cualquier número entero como semilla
resultado = generar_numeros_enteros_aleatorios(N, minimo, maximo, semilla)
print(resultado)  # Resultado: será el mismo cada vez que ejecutes el código con la misma semilla


[7, 4, 8, 5, 7]


## 4.Ejercicio

Generar una Secuencia de Números
Desarrolla una función llamada generar_secuencia_numerica que tome como entrada un valor mínimo minimo, un valor máximo maximo y un paso paso, y utilice NumPy para generar una secuencia de números en el rango [minimo, maximo) con el paso especificado.



def generar_secuencia_numerica(minimo, maximo, paso):

   

#### Ejemplo de uso
minimo = 0
maximo = 10
paso = 2
resultado = generar_secuencia_numerica(minimo, maximo, paso)
print(resultado)


Resultado

[0 2 4 6 8]

In [145]:
import numpy as np

def generar_secuencia_numerica(minimo, maximo, paso):
    return np.arange(minimo, maximo, paso)

# Ejemplo de uso
minimo = 0
maximo = 10
paso = 2
resultado = generar_secuencia_numerica(minimo, maximo, paso)

print(resultado)  


[0 2 4 6 8]
